import Image from 'next/image';
import DemoTool from './demo-tool';

const transformations = [
  ['Stay visible through your busiest weeks', 'A steady social presence keeps your business familiar—even when you’re too busy to think about posting.'],
  ['Look as polished online as you are in person', 'Every post carries your colors, style, and voice, without you opening a design tool.'],
  ['Turn ordinary moments into useful marketing', 'A delivery, a happy customer, today’s special—what already happens in your day becomes something worth sharing.'],
  ['Stay in control without staying involved', 'Approve each post, ask for a change, or let approved content go out automatically. You choose.'],
];

const faqs = [
  ['Do I need to know anything about social media?', 'Not at all. HiVaulted is designed for business owners who would rather focus on their actual work. Send a photo or a few words and we handle the post.'],
  ['Will the posts sound like me?', 'Yes. HiVaulted learns your tone, business, colors, and preferences so the finished content feels like your brand—not generic AI copy.'],
  ['Do posts publish without my approval?', 'Only if you want them to. You can approve every post, request edits, or choose automatic publishing once you feel comfortable.'],
  ['What if I have nothing to send?', 'That is part of the point. HiVaulted can help keep your presence moving even when you do not have a fresh photo or idea ready.'],
];

const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };

export default function Home() {
  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <header className="site-header">
        <a href="#top" aria-label="HiVaulted home" className="brand-link"><Image src="/hivaulted-horizontal.svg" alt="HiVaulted" width={244} height={52} priority /></a>
        <nav aria-label="Primary navigation"><a href="#how-it-works">How it works</a><a href="#demo">Try it</a><a href="#pricing">Pricing</a></nav>
        <a className="button button-small" href="https://app.hivaulted.com/">Get started</a>
      </header>

      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow"><span /> Social media, handled</p><h1>Your business keeps showing up. <em>You don’t have to.</em></h1><p className="hero-lede">HiVaulted turns the photos, ideas, and everyday moments from your business into polished social posts—so you stay visible without adding another job to your day.</p><div className="hero-actions"><a className="button" href="#demo">See what you could post <span aria-hidden="true">→</span></a><a className="text-link" href="#how-it-works">See how easy it is</a></div><ul className="reassurance" aria-label="HiVaulted benefits"><li><b>✓</b> No design skills</li><li><b>✓</b> No new routine</li><li><b>✓</b> You stay in control</li></ul></div>
        <div className="hero-stage" aria-label="Example of a HiVaulted social post"><div className="orbit-note note-one">Ready to post <b>✓</b></div><div className="orbit-note note-two">Sounds like you</div><article className="post-card"><div className="post-topline"><span className="avatar">BM</span><span><strong>Bloom &amp; Main</strong><small>Sponsored by a very full Saturday</small></span><span className="post-menu">•••</span></div><div className="post-photo"><div className="sun"/><div className="shop-awning"><i/><i/><i/><i/><i/></div><div className="shop-front"><span>OPEN</span></div><div className="plant plant-a">✦</div><div className="plant plant-b">✦</div></div><div className="post-copy"><div className="post-icons"><span>♡</span><span>◯</span><span>⌁</span><span className="bookmark">⌑</span></div><p><strong>bloomandmain</strong> The door is open, the coffee is hot, and the shelves are full of something special. Come say hi this Saturday. 💙</p><small>#shopsmall #saturdaylocal</small></div></article><div className="approval-card"><span className="mini-mark">H</span><p><strong>Your post is ready.</strong><small>Want us to send it out?</small></p><button type="button">Approve</button></div></div>
      </section>

      <section className="outcome-strip" aria-label="What HiVaulted helps you accomplish"><span>Stay visible</span><i>✦</i><span>Look professional</span><i>✦</i><span>Remain top of mind</span><i>✦</i><span>Get your time back</span></section>

      <section className="problem-section"><div className="problem-lead"><p className="eyebrow"><span /> Built for real business days</p><h2>You’re not bad at social media.<br/><em>It’s just not your actual job.</em></h2></div><div className="problem-copy"><p>Your customers still need to see you. But between serving them, managing the books, answering messages, and doing the work itself, “make a post” keeps sliding to tomorrow.</p><p><strong>HiVaulted closes that gap.</strong> Your business gets the consistent, professional presence it needs—and you get to keep your attention where it belongs.</p></div></section>

      <section className="steps-section" id="how-it-works"><div className="section-heading"><p className="eyebrow"><span /> From your day to their feed</p><h2>Three small steps.<br/>One less thing to carry.</h2><p>No complicated content calendar. No blank caption box. No learning curve.</p></div><div className="steps-grid"><article><span>01</span><div className="step-icon camera-icon">▣</div><h3>Send what you have</h3><p>A photo, a quick thought, a voice note, or a few words. Text or email it in and get back to your day.</p></article><article><span>02</span><div className="step-icon magic-icon">✦</div><h3>We make it post-ready</h3><p>HiVaulted shapes it into a polished image and caption that fit your brand and sound like you.</p></article><article><span>03</span><div className="step-icon check-icon">✓</div><h3>Approve—or let it go</h3><p>Give it a quick yes, ask for a change, or switch on automatic posting when you’re ready.</p></article></div><div className="tiny-promise"><b>From your phone.</b><span>•</span>No design software.<span>•</span>No new system to babysit.</div></section>

      <section className="transformation-section"><div className="transformation-heading"><p className="eyebrow light"><span /> What changes</p><h2>Social stops nagging you.<br/><em>Your business keeps moving.</em></h2></div><div className="transformation-grid">{transformations.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

      <section className="demo-section" id="demo"><div className="section-heading demo-heading"><p className="eyebrow"><span /> Try it for yourself</p><h2>See what your business<br/>could post next.</h2><p>Choose your business, add a few words, and watch one more thing come off your plate.</p></div><DemoTool /><p className="demo-privacy">No account needed to try it. Your image and message are used only to create this demo post.</p></section>

      <section className="control-section"><div className="control-visual"><div className="message-bubble bubble-a"><span>H</span><p>Your Saturday post is ready. Want to send it?</p></div><div className="message-bubble bubble-b"><p>Looks great 👍</p></div><div className="message-bubble bubble-c"><span>H</span><p>Done. Now go enjoy your coffee.</p></div></div><div className="control-copy"><p className="eyebrow"><span /> Easy does it</p><h2>Stay in control.<br/><em>Skip the busywork.</em></h2><p>HiVaulted meets you in the tools you already use. Review a post by text or email, ask for a change in plain English, or let approved content publish automatically.</p><ul><li><b>✓</b> Approve every post if you want</li><li><b>✓</b> Request changes without opening an editor</li><li><b>✓</b> Choose automatic posting when you’re ready</li></ul></div></section>

      <section className="award-section"><div className="award-medal">2026<span>AI</span></div><div><p className="eyebrow"><span /> Recognized innovation</p><h2>Built by someone who understands what busy business owners are up against.</h2><p>HiVaulted founder Anne Archer was named 2026 AI Innovator of the Year for the Minnesota/Wisconsin region of Coldwell Banker Realty.</p><small>Awarded to Anne Archer. Independent of Coldwell Banker Realty.</small></div></section>

      <section className="pricing-section" id="pricing"><div className="section-heading"><p className="eyebrow"><span /> Pre-launch pricing</p><h2>A small price for getting<br/>social off your plate.</h2><p>Choose the rhythm that works for your business. Every pre-launch option includes hands-on setup and your brand voice built in.</p></div><div className="pricing-grid"><article className="price-card"><p className="plan-kicker">Flexible</p><h3>Monthly pre-launch</h3><div className="price-label">Founding rate</div><p>For owners who want to start simply and keep things month to month.</p><ul><li>✓ Branded, ready-to-post content</li><li>✓ Caption and image creation</li><li>✓ Approval by text or email</li><li>✓ Hands-free scheduling</li></ul><a href="https://app.hivaulted.com/">See monthly option <span>→</span></a></article><article className="price-card featured"><div className="popular-tag">Best pre-launch value</div><p className="plan-kicker">Commit and save</p><h3>Annual pre-launch</h3><div className="price-label">Lowest founding rate</div><p>For owners ready to make consistent visibility part of the business.</p><ul><li>✓ Everything in monthly</li><li>✓ Your best available launch rate</li><li>✓ Priority onboarding support</li><li>✓ One less monthly decision</li></ul><a href="https://app.hivaulted.com/">See annual option <span>→</span></a></article></div><p className="pricing-note">Pre-launch availability is limited. Exact current rates are shown during account setup.</p></section>

      <section className="faq-section"><div><p className="eyebrow"><span /> Good questions</p><h2>The things you’re probably wondering.</h2><p>Still curious? Write to <a href="mailto:hello@hivaulted.com">hello@hivaulted.com</a>. A real person will get back to you.</p></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>＋</span></summary><p>{answer}</p></details>)}</div></section>

      <section className="final-cta"><div><p className="eyebrow light"><span /> Your business has enough to do</p><h2>Keep showing up.<br/><em>Lose the social media stress.</em></h2><p>Give HiVaulted a little. Get a polished, consistent social presence back.</p><div><a className="button button-green" href="https://app.hivaulted.com/">Take social off my plate <span>→</span></a><a href="#demo">Or try the demo again</a></div></div><div className="cta-stamp">POST<br/><span>SMARTER</span><small>RISE HIGHER</small></div></section>

      <footer><a href="#top" className="footer-logo"><Image src="/hivaulted-horizontal.svg" alt="HiVaulted" width={244} height={52} /></a><p>Social media support for people who’d rather be doing… literally anything else.</p><nav><a href="#how-it-works">How it works</a><a href="#demo">Demo</a><a href="#pricing">Pricing</a><a href="mailto:hello@hivaulted.com">Contact</a><a href="https://www.hivaulted.com/privacy-policy">Privacy</a><a href="https://www.hivaulted.com/terms-conditions">Terms</a></nav><div className="footer-bottom"><span>© 2026 HiVaulted™. All rights reserved.</span><span>Customized by you. Powered by thoughtful AI.</span></div></footer>
    </main>
  );
}
